"""Export a clean, publishable copy of Open Marketing OS (DEV-008).

Why this exists
---------------
The development repository is not the public repository. Alongside the product
it tracks a live marketing operation for a named third-party business —
`company/`, `knowledge/`, `production/`, `research/`, `creative/`, `execution/`,
`strategy/` — plus internal engineering history (`development/runs/`).

It also tracks `.agents/`, which is two different things in one directory, and
the difference is a licensing question rather than a taste question:

- `.agents/skills/**` is a **pinned, MIT-licensed upstream library**
  (`coreyhaines31/marketingskills`, tag `v2.11.1`, commit
  `5b2c0007766c6a1cf1d53fd8fc73e979e0821022`). MIT permits redistribution as
  long as the copyright and permission notice travel with the copies, so it
  ships — with the upstream `LICENSE` vendored verbatim at `.agents/LICENSE`.
- `.agents/product-marketing.md` is **OMOS-authored** and holds founder
  business material. It is not upstream, so shipping it would both launder
  OMOS-authored content under someone else's MIT grant and publish a named
  third party's Marketing Brain. It is withheld, and `audit_payload()` fails
  the export closed if it is ever requested.

The narrow include is therefore `.agents/skills/**` plus `.agents/LICENSE` and
nothing else, enforced twice: by what is listed below, and by a shape check on
anything under `.agents/` in `audit_payload()`.

The founder decision for DEV-008 was to publish to a **new, clean public
repository**. This script is that decision made mechanical and auditable: the
include/exclude lists below are the single source of truth, and the script
**fails closed** if it is ever asked to include a forbidden path.

It copies files; it never moves or deletes anything in the source tree, and it
never runs git commands. The founder creates the public repository from the
output.

Usage
-----
    python scripts/package/export_public_repo.py --out ../open-marketing-os-public
    python scripts/package/export_public_repo.py --out ..\\omos-public --dry-run
"""
from __future__ import annotations

import argparse
import fnmatch
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# --- the vendored upstream skills library (DEV-008-SKILLS-OPS) ----------------
#: The only `.agents/` subtree that is upstream.
#:
#: MIT permits redistribution provided the copyright and permission notice
#: travel with the copies, so the library is no longer a licensing problem --
#: it was never one, it was simply an unrecorded one. The obligation it creates
#: is why `AGENTS_LICENSE_FILE` ships next to it.
AGENTS_INCLUDE_ROOT = ".agents/skills"

#: The upstream `LICENSE`, vendored **verbatim** at this path. Not a copy of a
#: copy: the bytes are the upstream file at the pinned commit
#: (`5b2c0007766c6a1cf1d53fd8fc73e979e0821022`), which
#: `app/tests/test_dev008so_provenance_gate.py` re-hashes. `NOTICE` records the
#: repository, tag, commit and SPDX id in prose; this file is what actually
#: travels with the vendored copy, which is what MIT asks for.
AGENTS_LICENSE_FILE = ".agents/LICENSE"

#: `.agents/` paths that must never ship, whatever else changes.
#:
#: Kept as an explicit list (not merely "not in the include") so the failure
#: message can say *why*, and so the reason survives a later refactor.
AGENTS_WITHHELD = (
    # OMOS-authored, not upstream, and it contains a named third party's
    # Marketing Brain facts. It is Apache-2.0 like the rest of OMOS; publishing
    # it beside an MIT licence would misrepresent whose grant covers it.
    ".agents/product-marketing.md",
)

# --- top-level entries copied into the public repository --------------------
# Build output (`build/`, `dist/`) is deliberately absent: it is generated by
# scripts/package/*.ps1 and must never be committed. The public repository
# builds its own release assets in CI.
INCLUDE_ROOTS = (
    "app",              # the product backend
    "frontend",         # React source (ships prebuilt; node_modules excluded)
    "launcher",         # desktop launcher + process manager
    "packaging",        # PyInstaller spec + Inno Setup script
    # DEV-008: product configuration, NOT private material.
    #
    # `config/model_pricing.yaml` is read at runtime by ModelRouter on every
    # graph turn, `config/v1_runtime.yaml` is asserted by a product-contract
    # test, and both are bundled into the Windows payload. Leaving `config/`
    # out produced a public repository whose test suite failed on arrival and
    # whose build could not produce a working app.
    #
    # This is categorically different from `company/`, `production/`,
    # `strategy/` and `state/`, which hold the founder's private business
    # workspace and stay excluded.
    "config",
    # DEV-008-SKILLS-OPS: the pinned upstream marketing skills library, which is
    # MIT and therefore redistributable. Narrow on purpose -- the library
    # subtree only, never the whole `.agents/` directory. See
    # AGENTS_INCLUDE_ROOT / AGENTS_WITHHELD below and the module docstring.
    AGENTS_INCLUDE_ROOT,
)

#: Individual files under `scripts/` that a public contributor needs.
#:
#: DEV-008-PUBLISH-GATE. `scripts/` used to be exported wholesale, which shipped
#: the founder's private dogfood and evaluation tooling into the public
#: repository: `live_dogfood_gate.py`, `live_reproof_gate.py`, `live_social_ux.py`
#: and `workers/dev006_w*.py` alone accounted for ~90 references to a real named
#: business, its clients and its live Instagram handle.
#:
#: It also shipped `train_lora.py`, `train_dev006_lora.py`,
#: `train_dev006b_lora.py` and `benchmark_local_model.py` — training and
#: benchmarking tooling for a local-model edition that does not exist in this
#: beta. Publishing those next to a README that says "no local model in this
#: release" is a Gate 2 honesty failure as much as a privacy one.
#:
#: Only what is needed to *build, run and test the public project* is listed.
SCRIPT_ALLOWLIST = (
    "package/build_installer.ps1",
    "package/build_portable.ps1",
    "package/build_windows.ps1",
    "package/export_public_repo.py",
    "package/license_inventory.py",
    "package/make_manifest.py",
    "package/secret_scan.py",
    "package/sync_project_urls.py",
    "run-dev.ps1",
    "setup-dev.ps1",
    # The delegation scheduler. `docs/development-delegation-system.md` and
    # `docs/parallel-agent-execution.md` are both published, so the tooling they
    # describe has to be published too -- and `app/tests/test_dev_parallel.py`
    # imports it. Both files were verified to contain no private material.
    "dev_run.py",
    "dev_sched.py",
)

INCLUDE_FILES = (
    "LICENSE",
    "NOTICE",
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "CHANGELOG.md",
    ".gitignore",
    ".env.example",
    "app.py",
    "pytest.ini",
    "requirements.txt",
    "requirements-lock.txt",
    "requirements-dev.txt",
    "requirements-optional.txt",
    "start.bat",
    "start.sh",
    # The upstream MIT licence for the vendored skills library. Ships because
    # AGENTS_INCLUDE_ROOT ships.
    AGENTS_LICENSE_FILE,
)

# --- docs: explicit allowlist ------------------------------------------------
# `docs/` in the development repository is dominated by internal engineering
# history: gate packets, remediation reviews, founder handoff notes, worker DAGs
# and superseded v0.1/v0.2/v1 plans. A public reader needs none of that, and
# the mission is explicit that internal development history does not belong in
# public material.
#
# This is an ALLOWLIST, so a newly added doc is withheld by default rather than
# published by accident. Whatever is withheld is reported at the end of a run,
# so nothing is dropped silently.
DOCS_ALLOWLIST = (
    # user-facing
    "docs/architecture.md",
    "docs/user-data-and-backup.md",
    "docs/troubleshooting.md",
    "docs/privacy.md",
    # distribution and legal
    "docs/distribution/windows-packaging-decision.md",
    "docs/opensource/license-audit.md",
    # contributor-facing: how this project is actually built and reviewed
    "docs/development-delegation-system.md",
    "docs/parallel-agent-execution.md",
    # release history
    "docs/releases/v1.0.0.md",
)

#: Paths inside `docs/` that must never ship even if allowlisted by accident.
DOCS_DENYLIST = (
    "founder",
    "gate",
    "remediation",
    "review-packet",
    "lora-training-plan",
    "model-benchmark-plan",
    "worker-dag",
    "source-integrity",
)

#: Directories that are part of the public repository's own automation.
INCLUDE_DIRS = (".github",)

# --- never published ---------------------------------------------------------
#: Top-level paths that must never appear in the public repository. Listed
#: explicitly (rather than only as "everything not in INCLUDE") so that adding a
#: new top-level directory later cannot accidentally publish it.
FORBIDDEN_ROOTS = (
    "company",
    "knowledge",
    "production",
    "research",
    "creative",
    "execution",
    "strategy",
    "state",
    "analytics",
    "content",
    "templates",
    "workflows",
    "maintenance",
    "tests",           # founder marketing-evaluation material, NOT unit tests.
                       # The project's real test suite is app/tests/, which is
                       # exported with `app/`. This directory holds the founder's
                       # agency-pitch evaluations and outreach sequences for a
                       # named real business.
    # `.agents` is deliberately NOT in this list (DEV-008-SKILLS-OPS). The
    # pinned upstream skills library is MIT and is redistributed, with its
    # licence attached, via the narrow include `AGENTS_INCLUDE_ROOT` +
    # `AGENTS_LICENSE_FILE`. A blanket ban was the wrong control: it is why
    # 280 files of MIT-licensed material shipped with no licence record at all.
    # The control that replaces it is `agents_violation()` in `audit_payload()`,
    # which rejects any `.agents/` path outside those two shapes -- including
    # the OMOS-authored `AGENTS_WITHHELD` entries.
    ".opencode",
    ".dogfood-scratch",
    ".reproof-scratch",
    "development",
    "data",
    "build",
    "dist",
    ".venv",
)

#: Glob patterns excluded anywhere in the tree.
EXCLUDE_PATTERNS = (
    ".env", ".env.*", "*.pyc", "__pycache__", "*.pyo",
    "node_modules", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "*.db", "*.db-journal", "*.db-wal", "*.db-shm", "*.sqlite", "*.sqlite3",
    "*.gguf", "*.ggml", "*.safetensors", "*.onnx", "*.pt", "*.pth", "*.ckpt",
    "*.pem", "*.key", "*.p12", "*.pfx", "secrets.json", "credentials.json",
    "*.log", "*.ttf", "*.otf", "*.woff", "*.woff2", "*.eot",
    "*.jpg", "*.jpeg", "*.png", "*.webp", "*.gif",
    "*.exe", "*.dll", "*.msi", "*.zip", "*.7z",
    "execution.jsonl.tmp", "*.tmp",
    ".DS_Store", "Thumbs.db", "desktop.ini",
)

#: Frontend build output is produced by `npm run build`; it is not source.
EXCLUDE_DIR_NAMES = (
    "node_modules", "dist", "build", "__pycache__", ".pytest_cache",
)

#: Test fixture images that must not travel even though images are excluded
#: wholesale above. Kept as documentation of intent.
EXCLUDE_EXACT = ()

#: Exceptions that win over EXCLUDE_PATTERNS.
#:
#: `.env.example` is a committed template containing placeholders only — its
#: whole purpose is to be public. It is asserted placeholder-only by
#: `development/runs/DEV-008/secret_scan.py` and by the CI assertion that no
#: `.env` is tracked. Without this exception the generic `.env.*` glob would
#: silently drop the template from the public repository.
ALLOW_PATTERNS = (
    ".env.example",
)


class ExportError(RuntimeError):
    pass


def is_excluded(rel: Path) -> bool:
    parts = rel.parts
    name = rel.name
    if name in EXCLUDE_EXACT:
        return True
    if any(fnmatch.fnmatch(name, allow) for allow in ALLOW_PATTERNS):
        return False
    if any(part in EXCLUDE_DIR_NAMES for part in parts):
        return True
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


def plan(include_root: Path) -> list[Path]:
    """Files that would be copied, relative to ``include_root``."""
    selected: list[Path] = []
    for path in include_root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(include_root)
        if is_excluded(rel):
            continue
        selected.append(rel)
    return sorted(selected)


def fail_closed_check() -> None:
    """Refuse to run if an include entry is also a forbidden entry."""
    overlap = {p for p in INCLUDE_ROOTS if p in FORBIDDEN_ROOTS}
    if overlap:
        raise ExportError(
            "Refusing to export: these paths are both included and forbidden: "
            + ", ".join(sorted(overlap))
        )


def check_public_url_ready() -> list[str]:
    """Problems that must block a real publication run.

    DEV-008 review finding N5. The public repository's README download button,
    its two badges and the "latest release" link all point at whatever
    `app/project_urls.py` says. If that is still the *private* development
    repository — which it is until the founder creates the public one — every
    ordinary user gets a 404 on step one, and nothing else in the pipeline would
    notice.

    `--allow-placeholder-url` exists so a dry run or a rehearsal is still
    possible, but the default is to refuse.
    """
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from app import project_urls

    problems: list[str] = []
    if not project_urls.is_placeholder():
        return problems

    problems.append(
        "app.project_urls.PUBLIC_REPOSITORY_URL still points at the PRIVATE "
        f"development repository ({project_urls.PRIVATE_REPOSITORY_URL}). "
        "Set it to the new public repository and run "
        "scripts/package/sync_project_urls.py, then update the GitHub links in "
        "README.md. See founder-publication-runbook.md step 2."
    )
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    if project_urls.PRIVATE_REPOSITORY_URL in readme:
        problems.append(
            "README.md still links to the private repository, so the exported "
            "public repository would ship a download button that 404s for every "
            "ordinary user."
        )
    return problems


def agents_violation(name: str) -> str | None:
    """Reject any `.agents/` path outside the two redistributable shapes.

    `.agents/` is allowlisted **by shape**, not trusted wholesale. The library
    (`.agents/skills/**`) and the licence that must travel with it
    (`.agents/LICENSE`) are upstream MIT material. Everything else under
    `.agents/` is either OMOS-authored or unknown, and the directory has held
    both, so the directory is never the unit of trust.
    """
    if not (name == ".agents" or name.startswith(".agents/")):
        return None
    if name == AGENTS_LICENSE_FILE or name.startswith(AGENTS_INCLUDE_ROOT + "/"):
        return None
    if name in AGENTS_WITHHELD:
        return (
            f"{name} is withheld from the public repository: it is "
            f"OMOS-authored, not upstream, and must not be redistributed under "
            f"the upstream MIT grant"
        )
    return (
        f"unrecognised .agents/ path: {name}. Only "
        f"{AGENTS_INCLUDE_ROOT}/** and {AGENTS_LICENSE_FILE} are redistributable; "
        f"anything else under .agents/ must be classified before it ships."
    )


def audit_payload(names: list[str]) -> list[str]:
    """Second gate, after copying: assert nothing forbidden slipped through."""
    problems: list[str] = []
    top_levels = {name.split("/", 1)[0] for name in names}
    for forbidden in FORBIDDEN_ROOTS:
        if forbidden in top_levels:
            problems.append(f"forbidden top-level path present: {forbidden}")
    for name in names:
        violation = agents_violation(name)
        if violation:
            problems.append(violation)
        base = name.rsplit("/", 1)[-1]
        if any(fnmatch.fnmatch(base, allow) for allow in ALLOW_PATTERNS):
            continue
        for pattern in EXCLUDE_PATTERNS:
            if fnmatch.fnmatch(base, pattern):
                problems.append(f"excluded pattern matched: {name}")
                break
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True,
                        help="destination directory for the clean copy")
    parser.add_argument("--dry-run", action="store_true",
                        help="list what would be copied and write nothing")
    parser.add_argument("--allow-placeholder-url", action="store_true",
                        help="permit the export while PUBLIC_REPOSITORY_URL still "
                             "points at the private repository (rehearsals only; "
                             "a real publication must not use this)")
    args = parser.parse_args(argv)

    fail_closed_check()

    url_problems = check_public_url_ready()
    if url_problems and not args.allow_placeholder_url:
        print("Refusing to export. The public repository is not ready:", file=sys.stderr)
        for item in url_problems:
            print(f"  - {item}", file=sys.stderr)
        return 1
    for item in url_problems:
        print(f"WARNING: {item}", file=sys.stderr)

    out = Path(args.out).expanduser().resolve()
    if out.exists() and any(out.iterdir()):
        print(f"Refusing to write into a non-empty directory: {out}", file=sys.stderr)
        print("Choose an empty or new destination.", file=sys.stderr)
        return 1
    if REPO_ROOT == out or REPO_ROOT in out.parents:
        print("Refusing to export into the source repository.", file=sys.stderr)
        return 1

    files: list[Path] = []

    for name in INCLUDE_ROOTS:
        source = REPO_ROOT / name
        if not source.exists():
            print(f"  note: {name}/ not present, skipped")
            continue
        for rel in plan(source):
            files.append(Path(name) / rel)

    # scripts/ is an explicit allowlist, not a directory copy. See
    # SCRIPT_ALLOWLIST for why wholesale export was wrong.
    scripts_root = REPO_ROOT / "scripts"
    for rel in SCRIPT_ALLOWLIST:
        source = scripts_root / rel
        if not source.is_file():
            print(f"  note: scripts/{rel} not present, skipped")
            continue
        files.append(Path("scripts") / rel)
    withheld_scripts = sorted(
        p.relative_to(REPO_ROOT).as_posix()
        for p in scripts_root.rglob("*")
        if p.is_file()
        and p.relative_to(REPO_ROOT).as_posix() not in set(SCRIPT_ALLOWLIST)
        and not is_excluded(p.relative_to(scripts_root))
    )

    for name in INCLUDE_DIRS:
        source = REPO_ROOT / name
        if not source.is_dir():
            continue
        for rel in plan(source):
            files.append(Path(name) / rel)

    # docs/ is allowlisted. Withheld files are collected and reported so the
    # founder can see exactly what was left behind.
    withheld: list[str] = []
    docs_root = REPO_ROOT / "docs"
    if docs_root.is_dir():
        for candidate in sorted(docs_root.rglob("*")):
            if not candidate.is_file():
                continue
            rel_doc = candidate.relative_to(REPO_ROOT).as_posix()
            base = candidate.name.lower()
            if any(token in base or token in rel_doc.lower() for token in DOCS_DENYLIST):
                withheld.append(rel_doc)
                continue
            if rel_doc in DOCS_ALLOWLIST:
                if is_excluded(candidate.relative_to(docs_root)):
                    continue
                files.append(Path(rel_doc))
            else:
                withheld.append(rel_doc)

    for name in INCLUDE_FILES:
        source = REPO_ROOT / name
        if source.is_file():
            files.append(Path(name))
        else:
            print(f"  note: {name} not present, skipped")

    names = sorted({f.as_posix() for f in files})

    # Anything under `.agents/` that was not selected, reported by name. The
    # narrow include is data-driven: a file added to `.agents/` tomorrow is
    # withheld and visible, not silently dropped.
    selected = set(names)
    withheld_agents: list[str] = []
    agents_root = REPO_ROOT / ".agents"
    if agents_root.is_dir():
        for candidate in sorted(agents_root.rglob("*")):
            if not candidate.is_file():
                continue
            if is_excluded(candidate.relative_to(agents_root)):
                continue
            rel_agents = candidate.relative_to(REPO_ROOT).as_posix()
            if rel_agents not in selected:
                withheld_agents.append(rel_agents)

    problems = audit_payload(names)
    if problems:
        print("Refusing to export. The audit found:", file=sys.stderr)
        for item in sorted(set(problems)):
            print(f"  - {item}", file=sys.stderr)
        return 1

    total_bytes = sum((REPO_ROOT / rel).stat().st_size for rel in files)
    print(f"Planned {len(names)} files, {total_bytes / 1_048_576:.1f} MB")

    if withheld:
        print(f"\nWithheld {len(withheld)} docs/ files (internal engineering history):")
        for name in withheld:
            print(f"  - {name}")
        print("Add one to DOCS_ALLOWLIST in this script if it should be public.")

    if withheld_scripts:
        print(f"\nWithheld {len(withheld_scripts)} scripts/ files "
              f"(internal tooling, private dogfood data, or local-model "
              f"training for an edition that does not ship):")
        for name in withheld_scripts:
            print(f"  - {name}")
        print("Add one to SCRIPT_ALLOWLIST in this script if it should be public.")

    if withheld_agents:
        print(f"\nWithheld {len(withheld_agents)} .agents/ files "
              f"(not the pinned upstream library, and not the licence that "
              f"travels with it):")
        for name in withheld_agents:
            violation = agents_violation(name)
            print(f"  - {name}")
            if violation:
                print(f"      reason: {violation}")

    if args.dry_run:
        top_levels: dict[str, int] = {}
        for name in names:
            top_levels[name.split("/", 1)[0]] = top_levels.get(name.split("/", 1)[0], 0) + 1
        for key in sorted(top_levels):
            print(f"  {key:28s} {top_levels[key]:5d} files")
        if ".agents" in top_levels:
            print(
                f"\n.agents/ is a NARROW include: {AGENTS_INCLUDE_ROOT}/** plus "
                f"{AGENTS_LICENSE_FILE}, and nothing else. Upstream is "
                f"coreyhaines31/marketingskills v2.11.1 (MIT); see NOTICE."
            )
        print("\nDry run: nothing written.")
        return 0

    out.mkdir(parents=True, exist_ok=True)
    for rel in files:
        destination = out / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO_ROOT / rel, destination)

    # The public repository gets a .gitignore that also ignores `dist/` and
    # `build/`, which the shipped one already does.
    print(f"Exported {len(names)} files to {out}")
    print("Next steps for the founder are in the DEV-008 publication runbook.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
